In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
import os

In [ ]:
df = pd.read_excel("drive/MyDrive/platicas/NFL.xlsx", header=1)

In [ ]:
df.head()

Juego  Ofensiva  Defensiva  W - L  ... Ofensiva.1  Defensiva.1  W - L.1  L - V.1
0     1      23.0       34.0    0.0  ...       34.0         20.0      1.0        V
1     2      31.0       17.0    1.0  ...       23.0         20.0      1.0        L
2     3      28.0       10.0    1.0  ...       34.0         20.0      1.0        L
3     4      38.0       31.0    1.0  ...       26.0         10.0      1.0        V
4     5      19.0       20.0    0.0  ...       32.0         32.0      0.0        V

[5 rows x 9 columns]

In [ ]:
df.Juego.loc[17:18] = [18, 19]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


In [ ]:
df

Juego  Ofensiva  Defensiva  ...  Defensiva.1 W - L.1  L - V.1
0            1      23.0       34.0  ...         20.0     1.0        V
1            2      31.0       17.0  ...         20.0     1.0        L
2            3      28.0       10.0  ...         20.0     1.0        L
3            4      38.0       31.0  ...         10.0     1.0        V
4            5      19.0       20.0  ...         32.0     0.0        V
5            6      38.0       10.0  ...         17.0     1.0        L
6            7      45.0       20.0  ...         16.0     1.0        L
7            8      25.0       23.0  ...          9.0     1.0        V
8            9       3.0       38.0  ...         31.0     1.0        V
9           10      46.0       23.0  ...          NaN     NaN      NaN
10          11      24.0       27.0  ...         31.0     1.0        L
11          12      24.0       27.0  ...         24.0     1.0        L
12          13       NaN        NaN  ...         16.0     1.0        V
13          14      26.0       14.0  ...         27.0     1.0        L
14          15      31.0       27.0  ...         29.0     1.0        L
15          16      47.0        7.0  ...         14.0     1.0        V
16          17      44.0       27.0  ...         38.0     0.0        V
17          18      30.0       20.0  ...         17.0     1.0        V
18          19      31.0       26.0  ...         24.0     1.0        V
19  Super Bowl       NaN        NaN  ...          NaN     NaN      NaN

[20 rows x 9 columns]

In [ ]:
df = df.iloc[:19]
df

Juego  Ofensiva  Defensiva  W - L  ... Ofensiva.1  Defensiva.1  W - L.1  L - V.1
0      1      23.0       34.0    0.0  ...       34.0         20.0      1.0        V
1      2      31.0       17.0    1.0  ...       23.0         20.0      1.0        L
2      3      28.0       10.0    1.0  ...       34.0         20.0      1.0        L
3      4      38.0       31.0    1.0  ...       26.0         10.0      1.0        V
4      5      19.0       20.0    0.0  ...       32.0         32.0      0.0        V
5      6      38.0       10.0    1.0  ...       26.0         17.0      1.0        L
6      7      45.0       20.0    1.0  ...       43.0         16.0      1.0        L
7      8      25.0       23.0    1.0  ...       35.0          9.0      1.0        V
8      9       3.0       38.0    0.0  ...       33.0         31.0      1.0        V
9     10      46.0       23.0    1.0  ...        NaN          NaN      NaN      NaN
10    11      24.0       27.0    0.0  ...       35.0         31.0      1.0        L
11    12      24.0       27.0    0.0  ...       27.0         24.0      1.0        L
12    13       NaN        NaN    NaN  ...       22.0         16.0      1.0        V
13    14      26.0       14.0    1.0  ...       33.0         27.0      1.0        L
14    15      31.0       27.0    1.0  ...       32.0         29.0      1.0        L
15    16      47.0        7.0    1.0  ...       17.0         14.0      1.0        V
16    17      44.0       27.0    1.0  ...       21.0         38.0      0.0        V
17    18      30.0       20.0    1.0  ...       22.0         17.0      1.0        V
18    19      31.0       26.0    1.0  ...       38.0         24.0      1.0        V

[19 rows x 9 columns]

# Tampa Bay Bucaneers

In [ ]:
data = df.dropna()
dataX =data[["Juego"]]
X_train = np.array(dataX)
y_train = data['Ofensiva'].values

regr = linear_model.LinearRegression()

regr.fit(X_train, y_train)

y_pred = regr.predict(X_train)

print('Coeficiente: \n', regr.coef_)
print('Bo: \n', regr.intercept_)
print("Error cuadraro medio: %.2f" % mean_squared_error(y_train, y_pred))
print('R2: %.2f' % r2_score(y_train, y_pred))

Coeficiente: 
 [0.38444584]
Bo: 
 26.046914357682617
Error cuadraro medio: 104.33
R2: 0.04


In [ ]:
regr.predict([[20]])

array([26.5770361])

In [ ]:
data = df.dropna()
dataX =data[["Juego"]]
X_train = np.array(dataX)
y_train = data['Defensiva'].values

regr = linear_model.LinearRegression()

regr.fit(X_train, y_train)

y_pred = regr.predict(X_train)

print('Coeficiente: \n', regr.coef_)
print('Bo: \n', regr.intercept_)
print("Error cuadraro medio: %.2f" % mean_squared_error(y_train, y_pred))
print('R2: %.2f' % r2_score(y_train, y_pred))

Coeficiente: 
 [-0.03264064]
Bo: 
 22.555940386230056
Error cuadraro medio: 71.20
R2: 0.00


In [ ]:
regr.predict([[20]])


array([21.90312762])

In [ ]:
resultado = regr.coef_ * 20 + regr.intercept_
resultado

array([21.90312762])

### Kansas City Chiefs

In [ ]:
data = df.dropna()
dataX =data[["Juego"]]
X_train = np.array(dataX)
y_train = data['Ofensiva.1'].values

regr = linear_model.LinearRegression()

regr.fit(X_train, y_train)

y_pred = regr.predict(X_train)

print('Coeficiente: \n', regr.coef_)
print('Bo: \n', regr.intercept_)
print("Error cuadraro medio: %.2f" % mean_squared_error(y_train, y_pred))
print('R2: %.2f' % r2_score(y_train, y_pred))

Coeficiente: 
 [-0.25304366]
Bo: 
 32.544605373635605
Error cuadraro medio: 41.71
R2: 0.05


In [ ]:
regr.predict([[20]])


array([27.48373216])

In [ ]:
data = df.dropna()
dataX =data[["Juego"]]
X_train = np.array(dataX)
y_train = data['Defensiva.1'].values

regr = linear_model.LinearRegression()

regr.fit(X_train, y_train)

y_pred = regr.predict(X_train)

print('Coeficiente: \n', regr.coef_)
print('Bo: \n', regr.intercept_)
print("Error cuadraro medio: %.2f" % mean_squared_error(y_train, y_pred))
print('R2: %.2f' % r2_score(y_train, y_pred))

Coeficiente: 
 [0.42086482]
Bo: 
 18.159739714525607
Error cuadraro medio: 57.31
R2: 0.09


In [ ]:
regr.predict([[20]])


array([26.5770361])